name: Autograding Tests

on: [push, pull_request]  # Run tests on push and pull requests

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Ensures the repo files are available

    - name: Debug - List Repository Files
      run: ls -R  # Debugging step to check if test_assignment.py exists

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install pytest  # Install pytest explicitly

    - name: Run Pytest on test_assignment.py
      run: pytest test_assignment.py  # Run the tests on test_assignment.py
      continue-on-error: true  # Allow this to fail without stopping the workflow

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_ASSIGNMENT-PY_RESULTS: "${{ steps.test_assignment-py.outputs.result }}"
      with:
        runners: test_assignment-py