name: Autograding Tests

on: [push, pull_request]  # Run tests on push and PRs

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: pip install pytest  # ✅ Fix typo here
    
    - name: Run Pytest
      run: pytest test_assignment.py  # ✅ Explicitly run tests
    
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_ASSIGNMENT-PY_RESULTS: "${{ steps.test_assignment-py.outputs.result }}"
      with:
        runners: test_assignment-py
