name: Autograding Tests
'on': [push]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_assignment.py
      id: test_assignment-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        setup-command: pip install numpy pandas pytest pytest-json-report
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_ASSIGNMENT-PY_RESULTS: "${{steps.test_assignment-py.outputs.result}}"
      with:
        runners: test_assignment-py